import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

IMAGE_BOX = 75 * mm


def _scaled_image(path: str) -> Image:
    img = Image(path)
    ratio = img.imageWidth / img.imageHeight
    if ratio >= 1:
        img.drawWidth = IMAGE_BOX
        img.drawHeight = IMAGE_BOX / ratio
    else:
        img.drawHeight = IMAGE_BOX
        img.drawWidth = IMAGE_BOX * ratio
    return img


def generate_inspection_report(inspection: dict) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Edge Anomaly Detection Dashboard — Inspection Report", styles["Title"]))
    story.append(
        Paragraph(
            f"{inspection['component_display_name']} — {inspection['instance_label']}",
            styles["Heading2"],
        )
    )
    story.append(Spacer(1, 6 * mm))

    is_critical = bool(inspection["is_critical"])
    status_text = "CRITICAL DEFECT" if is_critical else "Normal"
    status_color = colors.red if is_critical else colors.green

    meta_table = Table(
        [
            ["Inspection ID", str(inspection["id"])],
            ["Timestamp", inspection["timestamp"]],
            ["Reconstruction Error", f"{inspection['error_percentage']:.2f}%"],
            ["Status", status_text],
        ],
        colWidths=[50 * mm, 100 * mm],
    )
    meta_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("TEXTCOLOR", (1, 3), (1, 3), status_color),
                ("FONTNAME", (1, 3), (1, 3), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 8 * mm))

    images_row = [
        [_scaled_image(inspection["raw_image_abs_path"]), _scaled_image(inspection["heatmap_abs_path"])],
        [Paragraph("Captured Image", styles["Normal"]),
         Paragraph("Anomaly Heatmap — JET colormap, red = high reconstruction error", styles["Normal"])],
    ]
    images_table = Table(images_row, colWidths=[IMAGE_BOX + 5 * mm, IMAGE_BOX + 5 * mm])
    images_table.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER")]))
    story.append(images_table)
    story.append(Spacer(1, 10 * mm))

    story.append(
        Paragraph(
            f"Generated by Edge Anomaly Detection Dashboard on "
            f"{datetime.now(timezone.utc).isoformat()}",
            styles["Italic"],
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer
